# 💝 環友科技專案贊助資訊

# 您可以通過以下方式支持環友科技的開源專案發展

# 🏢 企業贊助
# 如果您的企業希望支持我們的開源工作，請聯繫我們討論企業贊助方案
custom: ['https://www.utk.com.tw/contact', 'mailto:sen@utk.com.tw']

# 💼 專業服務
# 環友科技提供專業的軟體開發和技術諮詢服務
# 詳情請訪問我們的官方網站或直接聯繫我們

# 📧 聯繫方式
# - 官方網站: https://www.utk.com.tw/
# - 技術諮詢: sen@utk.com.tw  
# - GitHub: https://github.com/UTK-TW

# 🎯 支持方式
# 除了資金支持，您也可以通過以下方式支持我們：
# - ⭐ 為專案加星標
# - 🐛 回報錯誤和問題
# - 💡 提出功能建議
# - 📝 改進文檔
# - 🔧 貢獻程式碼
# - 📢 分享和推廣專案

# 🙏 感謝每一位支持環友科技開源專案的朋友！