# 🚀 Release Automation

name: 📦 自動化版本發布

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: 📦 Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          make_latest: true

